"""
TAO Autonomous Trading Bot — FastAPI backend (port 8001)
"""
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from core.config import settings
from db.database import init_db
from services.price_service import price_service
from services.strategy_service import DEFAULT_STRATEGIES
from services.activity_service import seed_startup as seed_activity
from services.cycle_service import cycle_service
from services.agent_service import agent_service
from services.bittensor_service import bittensor_service
from services.subnet_router import set_primary_validator
from services.promotion_service import promotion_service
from services.subnet_cache_service import subnet_cache_service
from services.webhook_service import webhook_service
from services import signal_ingestor
from routers import bot, trades, price, strategies, fleet, analytics, market, consensus, agent, alerts, wallet, pnl, override
from routers import webhooks as webhooks_router
from routers import signal_feeds as signal_feeds_router

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)


# ── Startup / Shutdown ──────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Startup sequence designed to pass Railway healthchecks:
    - ALL setup is wrapped in try/except so crashes don't prevent yield
    - yield happens as early as possible → /health is reachable immediately
    - Heavy services (chain, cycles, agents) start in background AFTER yield
    """
    import asyncio as _aio
    import os as _os

    logger.info("=== TAO Trading Bot starting ===")
    from core.config import settings as _settings
    _db_display = _settings.DATABASE_URL.split("@")[-1] if "@" in _settings.DATABASE_URL else _settings.DATABASE_URL
    logger.info(f"PORT={_os.environ.get('PORT', 'NOT SET')} DB={_db_display}")

    # ── DB init (required, but catch failures) ──────────────────────────────
    try:
        await init_db()
        logger.info("Database initialised")
    except Exception as _e:
        logger.error(f"DB init failed: {_e} — continuing with degraded mode")

    # ── OpenClaw round counter restore is DEFERRED ──────────────────────────
    # Session XXVII (2026-05-12): moved to AFTER the FORCE_PAPER_MODE wipe
    # block. Previously loaded BEFORE the wipe, which caused a race:
    #   1. load_from_db() pulls old round counter into consensus_service
    #   2. wipe zeroes BotConfig.openclaw_* columns in DB
    #   3. next consensus round _persist_to_db() writes in-memory (pre-wipe)
    #      counter back to DB, obliterating the wipe.
    # Loading after the wipe ensures consensus_service reads the zeroed row.

    # ── Seed default strategies ──────────────────────────────────────────────
    try:
        await seed_strategies()
    except Exception as _e:
        logger.error(f"Strategy seed failed: {_e}")

    # ── Seed activity log ────────────────────────────────────────────────────
    try:
        seed_activity()
    except Exception as _e:
        logger.error(f"Activity seed failed: {_e}")

    # ── Load webhook configs ─────────────────────────────────────────────────
    try:
        webhook_service.load()
        logger.info(f"WebhookService: {webhook_service.get_status()['count']} endpoint(s) loaded")
    except Exception as _e:
        logger.warning(f"WebhookService load failed: {_e}")

    # ── Load primary validator from config ───────────────────────────────────
    try:
        from sqlalchemy import select
        from db.database import AsyncSessionLocal
        from models.bot_config import BotConfig
        async with AsyncSessionLocal() as db:
            result = await db.execute(select(BotConfig).where(BotConfig.id == 1))
            cfg = result.scalar_one_or_none()
            if cfg and cfg.target_validator_hotkey:
                set_primary_validator(cfg.target_validator_hotkey)
                logger.info(f"Primary validator loaded: {cfg.target_validator_hotkey[:20]}…")
            else:
                logger.warning("No target_validator_hotkey in config — paper mode until set")
    except Exception as _e:
        logger.error(f"Validator load failed: {_e}")

    # ── FORCE_PAPER_MODE env var — reset strategies + wipe biased stats ──────
    # When FORCE_PAPER_MODE=1 is set in Railway environment:
    #   1. In-memory override flag set True (blocks all live execution)
    #   2. All strategies reset to PAPER_ONLY in DB (persistent)
    #   3. All strategy performance stats wiped (win_rate, pnl, cycles)
    #      — old stats were generated by the biased simulation and are
    #        meaningless. Clean slate for the honest simulation.
    import os as _os2
    if _os2.environ.get("FORCE_PAPER_MODE", "0") == "1":
        try:
            from sqlalchemy import update
            from db.database import AsyncSessionLocal
            from models.strategy import Strategy
            from models.trade import Trade
            from models.bot_config import BotConfig
            from services.cycle_service import set_force_paper_mode
            set_force_paper_mode(True)
            from datetime import datetime, timezone as _tz
            from sqlalchemy import select as _select
            from models.strategy import Strategy as _Strategy
            _reset_ts = datetime.now(_tz.utc)

            # ── FOSSIL CLEANUP THRESHOLD ──────────────────────────────────────
            # Any strategy whose stats_reset_at is older than this timestamp is
            # considered to be carrying legacy biased-sim data in the `trades`
            # table (from the pre-fossil-wipe era). Bumping this constant forces
            # a one-time re-wipe on next deploy. After the wipe, stats_reset_at
            # is stamped with a value > threshold and subsequent restarts skip.
            #
            # Session XXVI (2026-05-12): TRUE CLEAN SLATE.
            #   Prior wipe (Session XXV, May 11) only zeroed Strategy counters
            #   and the trades table — NOT BotConfig singleton. Dashboard was
            #   showing drifted counts immediately after deploy because:
            #     • BotConfig.total_trades was never reset
            #     • cycle_service.py writes Trade rows + increments Strategy
            #       counters but never touches BotConfig
            #     • trading_service.py is the only writer to BotConfig
            #   Result: 3 counters, 3 different sources of truth.
            #
            # Session XXVII (2026-05-12, late): ROUND COUNTERS ADDED.
            #   The XXVI wipe missed the OpenClaw fields (openclaw_total_rounds,
            #   openclaw_approved_rounds, openclaw_rejected_rounds) on BotConfig.
            #   Combined with the load/wipe ordering race in main.py startup,
            #   consensus_service persisted pre-wipe round counters back to DB
            #   after every consensus round, so "Total Rounds" stayed high
            #   (13,569 observed). Fixed here by:
            #     (a) zeroing the openclaw_* fields in this wipe,
            #     (b) deferring consensus_service.load_from_db() to AFTER wipe,
            #     (c) bumping threshold so wipe re-runs once on next deploy.
            FOSSIL_CLEANUP_THRESHOLD = datetime(2026, 5, 12, 20, 40, 0, tzinfo=_tz.utc)

            async with AsyncSessionLocal() as db:
                _existing = await db.execute(_select(_Strategy).limit(1))
                _first = _existing.scalar_one_or_none()
                _needs_wipe = (
                    _first is None
                    or _first.stats_reset_at is None
                    or _first.stats_reset_at < FOSSIL_CLEANUP_THRESHOLD
                )

                if _needs_wipe:
                    # Full wipe — zero ALL strategy counters AND delete paper trades
                    await db.execute(update(Strategy).values(
                        mode             = "PAPER_ONLY",
                        cycles_completed = 0,
                        win_trades       = 0,
                        loss_trades      = 0,
                        total_trades     = 0,
                        win_rate         = 0.0,
                        total_pnl        = 0.0,
                        avg_return       = 0.0,
                        stats_reset_at   = _reset_ts,
                    ))
                    # Purge paper trades from trades table (no tx_hash = paper)
                    # Live on-chain trades are preserved (tx_hash IS NOT NULL).
                    _del_result = await db.execute(
                        Trade.__table__.delete().where(Trade.tx_hash.is_(None))
                    )
                    # Session XXVI: zero BotConfig singleton counters.
                    # Session XXVII: ALSO zero OpenClaw round counters — the
                    # prior wipe left them intact, so "Total Rounds" kept
                    # climbing. consensus_service.load_from_db() is now called
                    # AFTER this block (see below), so it reads zeros.
                    _bot_reset = await db.execute(update(BotConfig).values(
                        total_trades             = 0,
                        successful_trades        = 0,
                        total_pnl                = 0.0,
                        daily_trades             = 0,
                        openclaw_total_rounds    = 0,
                        openclaw_approved_rounds = 0,
                        openclaw_rejected_rounds = 0,
                    ))
                    logger.warning(
                        f"FORCE_PAPER_MODE: TRUE CLEAN SLATE (Session XXVII) — "
                        f"zeroed {12} Strategy rows + deleted "
                        f"{_del_result.rowcount} paper trades + "
                        f"reset {_bot_reset.rowcount} BotConfig singleton "
                        f"(incl. OpenClaw round counters). "
                        f"New Zero Day: {_reset_ts.isoformat()}."
                    )
                else:
                    # Already clean — only enforce PAPER_ONLY mode, preserve honest stats
                    await db.execute(update(Strategy).values(mode = "PAPER_ONLY"))
                    logger.info("FORCE_PAPER_MODE: mode enforced, accumulated honest stats preserved")
                await db.commit()
            logger.warning(
                "FORCE_PAPER_MODE=1 — strategies reset to PAPER_ONLY, "
                "fossil data purged, honest simulation active"
            )
        except Exception as _e:
            logger.error(f"Force paper mode startup reset failed: {_e}")

    # ── Restore OpenClaw round counter from DB (DEFERRED) ────────────────────
    # Runs AFTER the FORCE_PAPER_MODE wipe so that when a wipe happens, the
    # consensus_service loads zeroed counters into memory instead of the
    # pre-wipe values (which would otherwise be persisted back and undo the
    # wipe on the next round). Session XXVII fix.
    try:
        from services.consensus_service import consensus_service as _cs
        await _cs.load_from_db()
    except Exception as _e:
        logger.warning(f"OpenClaw round counter restore failed: {_e}")

    # ── Schedule all heavy services as background task ───────────────────────
    # Fires AFTER yield — guarantees /health responds before any I/O starts.
    async def _boot_services():
        await _aio.sleep(3)  # let healthcheck pass first

        # Signal ingestor (Discord, Taostats, etc.) starts immediately —
        # it has no dependency on Finney/bittensor and should never be blocked by it.
        try:
            await signal_ingestor.start_all()
        except Exception as _e:
            logger.error(f"SignalIngestor start failed: {_e}")

        # Finney chain probe omitted at boot — bittensor's substrate-interface
        # blocks the event loop thread on connect. The cycle service handles
        # reconnection automatically once running.

        try:
            await price_service.start()
            logger.info("Price feed started")
        except Exception as _e:
            logger.error(f"Price feed start failed: {_e}")

        # Services that require Finney chain access run as fire-and-forget tasks.
        # bittensor's substrate-interface blocks the event loop thread on connect;
        # running them as tasks lets Discord Gateway and other async work proceed.
        async def _start_chain_services():
            await _aio.sleep(1)
            try:
                await subnet_cache_service.start()
                logger.info("Subnet cache started — real on-chain data active")
            except Exception as _e:
                logger.error(f"Subnet cache start failed: {_e}")

            await _aio.sleep(3)

            try:
                from routers.fleet import _RISK_CONFIG as _RC
                _cycle_interval = max(30, int(_RC.get("cycle_interval_seconds", 300)))
                await cycle_service.start(interval_seconds=_cycle_interval)
                logger.info(f"Cycle engine started — interval={_cycle_interval}s")
            except Exception as _e:
                logger.error(f"Cycle engine start failed: {_e}")

            try:
                await agent_service.start(interval=300)
                logger.info("Agent orchestrator started")
            except Exception as _e:
                logger.error(f"Agent start failed: {_e}")

            try:
                await promotion_service.start()
                logger.info("Promotion engine started")
            except Exception as _e:
                logger.error(f"Promotion engine start failed: {_e}")

        _aio.create_task(_start_chain_services())

    _aio.create_task(_boot_services())

    logger.info("=== Lifespan ready — /health is live ===")
    yield  # ← Railway healthcheck passes from here

    # ── Graceful shutdown ────────────────────────────────────────────────────
    logger.info("Shutting down services…")
    for svc in [promotion_service, agent_service, cycle_service, price_service, subnet_cache_service]:
        try:
            await svc.stop()
        except Exception as _e:
            logger.error(f"Stop failed for {svc}: {_e}")


async def seed_strategies():
    """Insert default strategy rows if they don't exist."""
    from db.database import AsyncSessionLocal
    from sqlalchemy import select
    from models.strategy import Strategy

    async with AsyncSessionLocal() as db:
        for s in DEFAULT_STRATEGIES:
            result = await db.execute(
                select(Strategy).where(Strategy.name == s["name"])
            )
            existing = result.scalar_one_or_none()
            if not existing:
                db.add(
                    Strategy(
                        name=s["name"],
                        display_name=s["display_name"],
                        description=s["description"],
                        parameters=s["parameters"],
                        is_active=s.get("is_active", False),
                        mode=s.get("mode", "PAPER_ONLY"),
                        win_trades=s.get("win_trades", 0),
                        loss_trades=s.get("loss_trades", 0),
                        total_trades=s.get("total_trades", 0),
                        win_rate=s.get("win_rate", 0.0),
                        total_pnl=s.get("total_pnl", 0.0),
                        cycles_completed=s.get("cycles_completed", 0),
                    )
                )
        await db.commit()
    logger.info("Strategies seeded — 12 strategies initialised")


# ── App ─────────────────────────────────────────────────────────────────────

app = FastAPI(
    title=settings.APP_NAME,
    version=settings.APP_VERSION,
    description="Autonomous TAO trading bot on Bittensor Finney mainnet",
    lifespan=lifespan,
)

# CORS — allow all origins unconditionally so Railway / any deployment works
# without environment variable coordination between frontend and backend services.
# POST preflights (OPTIONS) from any domain will be accepted.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,   # must be False when allow_origins=["*"]
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(bot.router)
app.include_router(trades.router)
app.include_router(price.router)
app.include_router(strategies.router)
app.include_router(fleet.router)
app.include_router(analytics.router)
app.include_router(market.router)
app.include_router(consensus.router)
app.include_router(agent.router)
app.include_router(alerts.router)
app.include_router(wallet.router)
app.include_router(pnl.router)
app.include_router(override.router)
app.include_router(webhooks_router.router)
app.include_router(signal_feeds_router.router)


@app.get("/")
async def root():
    return {
        "name": settings.APP_NAME,
        "version": settings.APP_VERSION,
        "status": "online",
        "docs": "/docs",
    }


@app.get("/health")
async def health():
    return {"status": "healthy"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host=settings.HOST,
        port=settings.PORT,
        reload=settings.DEBUG,
    )